camera_obstacle_node:
  ros__parameters:
    input_topic: "/detection/objects_3d_base"
    output_obstacles_topic: "/obstacles/camera_detected"
    output_markers_topic: "/obstacles/camera_markers"

    target_classes:
      - "person"
      - "box"
      - "bottle"
      - "chair"

    min_x: 0.1
    max_x: 8.0
    max_abs_y: 3.0
    min_confidence: 0.6

    marker_radius: 0.25
    log_period: 1.0